---

- hosts: all
  become: true
  tasks:

  - name: Update Repository Index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu" and ansible_architecture == "x86_64"

  - name: Update Repository Index
    dnf:
      update_cache: yes
    when: ansible_distribution == "Rocky" and ansible_architecture == "x86_64"

  - name: Install Apache
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu" and ansible_architecture == "x86_64"

  - name: Add php support for Apache
    apt:
       name: libapache2-mod-php
       state: latest
    when: ansible_distribution == "Ubuntu" and ansible_architecture == "x86_64"

  - name: Install Htop
      apt:
        name: htop
        state: latest
    when: ansible_distribution == "Ubuntu" and ansible_architecture == "x86_64"

  - name: Install Apache
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "Rocky" and ansible_architecture == "x86_64"

  - name: Add php support for Apache
    dnf:
       name: php
       state: latest
    when: ansible_distribution == "Rocky" and ansible_architecture == "x86_64"

  - name: Install Htop
      dnf:
        name: htop
        state: latest
    when: ansible_distribution == "Rocky" and ansible_architecture == "x86_64"
