---

- hosts: all
  become: true
  tasks:

  - name: Update Repository Index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu" and ansible_architecture == "x86_64"

  - name: Update Repository Index
    dnf:
      update_cache: yes
    when: ansible_distribution == "Rocky" and ansible_architecture == "x86_64"

  - name: Install Apache + php support and Htop packages
    apt:
      name:
        - apache2
        - libapache2-mod-php
        - htop
      state: latest
    when: ansible_distribution == "Ubuntu" and ansible_architecture == "x86_64"

  - name: Install Apache + php support and Htop packages
    dnf:
      name:
        - httpd
        - php
        - htop
      state: latest
    when: ansible_distribution == "Rocky" and ansible_architecture == "x86_64"
