---

- hosts: all
  become: true
  tasks:

  - name: Update Repository Index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Update Repository RedHat
    dnf:
      update_cache: yes
    when: ansible_distribution == "Rocky"

  - name: Install Apache
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Add php support for Apache
    apt:
       name: libapache2-mod-php
       state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Install Apache
    dnf:
      name: apache2
      state: latest
    when: ansible_distribution == "Rocky"

  - name: Add php support for Apache
    dnf:
       name: libapache2-mod-php
       state: latest
    when: ansible_distribution == "Rocky"
